# Clippy configuration for devstrap
# Per PROGRAMMING_V2.md: Functions ≤50 lines, files ≤150 lines (with exceptions)

# Maximum lines for functions/methods (PROGRAMMING_V2.md: ≤50)
too-many-lines-threshold = 50
